import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios';

import {useState, useEffect} from 'react';

export async function getServerSideProps(ctx: any) {
  // redirect the user to the app
  return {
    redirect: {
      destination: '/app',
      permanent: false
    }
  }
}


export default function Home() {

  return (
    <>
      <Head>
        <title>BroadcastMed x Pingplotter MultiViewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}
